name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    paths-ignore:
      - 'papers/**'
      # do not run CI if we are writing a paper
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
    branches:
      - 'master'
  schedule:
    - cron: "0 13 * * 1"
    # https://jasonet.co/posts/scheduled-actions/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-latest
          - ubuntu-20.04
        ocaml-version:
          #- 4.11.0
          - 4.10.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve date for cache key
        id: cache-key
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          # invalidate cache daily, gets built daily using a scheduled job
          key: ${{ steps.cache-key.outputs.date }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add OCanren.dev . --no-action
      - run: opam depext OCanren.dev --yes --with-test
      - run: opam install . --deps-only --with-test
      - run: opam exec -- make #dune build
      - run: opam exec -- make test # dune runtest
